command_timeout = 1000

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
${custom.haskell_version}\
${custom.haskell_compiler}\
$nodejs\
$python\
$rust\
$aws\
$env_var\
$sudo\
$fill\
$time\
$cmd_duration\
$line_break\
$character\
"""
add_newline = false

[fill]
disabled = false
symbol = "."
style = "bold black"

[time]
disabled = false
time_format = "%T"
utc_time_offset = "+11"

[cmd_duration]
disabled = false

[custom.haskell_version]
disabled = false
description = "Haskell project version"
command = "yq -r .version package.yaml"
detect_files = ["package.yaml"]
detect_extensions = ["hs"]
symbol = "ðŸ“¦ "
style = "gray"
format = "is [$symbol($output)]($style) "

[custom.haskell_compiler]
disabled = false
description = "Haskell compiler version"
command = "stack ghc -- --version | grep -Eo '[0-9.]+'"
detect_files = ["package.yaml", "stack.yaml"]
detect_extensions = ["hs"]
symbol = "Î»= "
style = "yellow"
format = "via [$symbol($output)]($style) "